from petisco.domain.errors.critical_error import CriticalError


class EventChaosError(CriticalError):
    pass
